- name: Set credentials to access Zabbix Server API
  set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix

- name: Create trigger-actions
  community.zabbix.zabbix_action:
    name: "{{ item.name }}"
    event_source: 'trigger'
    esc_period: "{{ item.esc_period }}"
    conditions: "{{ item.conditions }}"
    formula: "{{ item.formula }}"
    operations: "{{ item.operations }}"
    recovery_operations: "{{ item.recovery_operations }}"
    status: "{{ item.status }}"
    state: "{{ item.state }}"
  loop: "{{ zabbix_webapi_trigger_actions }}"