- name: Set credentials to access Zabbix Server API
  set_fact:
    ansible_user: "{{ zabbix_webapi_user }}"
    ansible_httpapi_pass: "{{ zabbix_webapi_pass }}"

- name: Create host groups.
  community.zabbix.zabbix_group:
    state: "{{ item.state }}"
    host_groups: "{{ item.groups }}"
  loop: "{{ zabbix_webapi_hostgroups }}"

- name: Create hosts.
  community.zabbix.zabbix_host:
    state: "{{ item.state }}"
    status: "{{ item.status }}"
    host_name: "{{ item.host_name }}"
    visible_name: "{{ item.visible_name }}"
    description: "{{ item.description }}"
    host_groups: "{{ item.host_groups }}"
    link_templates: "{{ item.link_templates }}"
    interfaces: "{{ item.interfaces }}"
    macros: "{{ item.macros }}"
    tags: "{{ item.tags }}"
  loop: "{{ zabbix_webapi_hosts }}"
 