- name: Create host groups.
  local_action:
    module: community.zabbix.zabbix_group
    server_url: "{{ zabbix_webapi_url }}"
    login_user: "{{ zabbix_webapi_user }}"
    login_password: "{{ zabbix_webapi_pass }}"
    state: "{{ item.state }}"
    host_groups: "{{ item.groups }}"
  loop: "{{ zabbix_webapi_hostgroups }}"

- name: Create hosts.
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "{{ zabbix_webapi_url }}"
    login_user: "{{ zabbix_webapi_user }}"
    login_password: "{{ zabbix_webapi_pass }}"
    state: "{{ item.state }}"
    status: "{{ item.status }}"
    host_name: "{{ item.host_name }}"
    visible_name: "{{ item.visible_name }}"
    description: "{{ item.description }}"
    host_groups: "{{ item.host_groups }}"
    link_templates: "{{ item.link_templates }}"
    interfaces: "{{ item.interfaces }}"
    macros: "{{ item.macros }}"
    tags: "{{ item.tags }}"
  loop: "{{ zabbix_webapi_hosts }}"
 