- name: Set credentials to access Zabbix Server API
  set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix

- name: Create Email mediatype.
  zabbix_mediatype:
    type: email 
    name: "{{ item.name }}"
    smtp_server: "{{ item.smtp_server }}"
    smtp_server_port: "{{ item.smtp_server_port }}"
    smtp_helo: "{{ item.smtp_helo }}"
    smtp_email: "{{ item.smtp_email }}"
    status: "{{ item.status }}"
    state: "{{ item.state }}"
  loop: "{{ zabbix_webapi_mediatypes }}"

- name: Create script mediatype.
  zabbix_mediatype:
    type: script
    name: "{{ item.name }}"
    script_name: "{{ item.script_name }}" 
    script_params: "{{ item.script_params }}"
    status: "{{ item.status }}"
    state: "{{ item.state }}"
  loop: "{{ zabbix_webapi_scripts }}"

- name: Create usergroups.
  community.zabbix.zabbix_usergroup:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    rights: "{{ item.rights }}"
    tag_filters: "{{ item.tag_filters }}"
  loop: "{{ zabbix_webapi_usergroups }}"

- name: Create user
  community.zabbix.zabbix_user:
    state: "{{ item.state }}"
    username: "{{ item.username }}"
    name: "{{ item.name }}"
    surname: "{{ item.surname }}"
    usrgrps: "{{ item.usrgrps }}"
    passwd: "{{ item.passwd }}"
    lang: "{{ item.lang }}"
    theme: "{{ item.theme }}"
    autologin: "{{ item.autologin }}"
    autologout: "{{ item.autologout }}"
    refresh: "{{ item.refresh }}"
    rows_per_page: "{{ item.rows_per_page }}"
    after_login_url: "{{ item.after_login_url }}"
    user_medias: "{{ item.user_medias }}"
    role_name: "{{ item.role_name }}"
  loop: "{{ zabbix_webapi_users }}"